export type ToolCategory = "all" | "content" | "seo" | "social" | "ecommerce" | "automation" | "analytics";

export type ToolAlternative = {
  name: string;
  cue: string;
};

export type AiTool = {
  id: string;
  slug: string;
  name: string;
  initials: string;
  tagline: string;
  description: string;
  category: Exclude<ToolCategory, "all">;
  categoryLabel: string;
  bestFor: string;
  pricingCue: string;
  tags: string[];
  alternatives: ToolAlternative[];
  featured?: boolean;
  verified?: boolean;
  ctaLabel: string;
  searchTerms: string[];
  seoTitle: string;
  seoDescription: string;
};

export const toolCategories: Array<{ id: ToolCategory; label: string }> = [
  { id: "all", label: "All" },
  { id: "content", label: "Content & Creative" },
  { id: "seo", label: "SEO & Research" },
  { id: "social", label: "Social Growth" },
  { id: "ecommerce", label: "Ecommerce" },
  { id: "automation", label: "Automation" },
  { id: "analytics", label: "Analytics & Conversion" },
];

export const aiTools: AiTool[] = [
  {
    id: "tool-chatgpt",
    slug: "chatgpt",
    name: "ChatGPT",
    initials: "CG",
    tagline: "Campaign ideas, drafts, and workflow support",
    description: "Plan content angles, rewrite landing copy, summarize research, and turn rough campaign notes into useful assets.",
    category: "content",
    categoryLabel: "Content & Creative",
    bestFor: "Creators, founders, marketers",
    pricingCue: "Free start",
    tags: ["Writing", "Ideation"],
    alternatives: [
      { name: "Claude", cue: "Long-form drafting" },
      { name: "Gemini", cue: "Google workflow" },
      { name: "Perplexity", cue: "Research" },
    ],
    featured: true,
    verified: true,
    ctaLabel: "View tool",
    searchTerms: ["chatgpt alternative", "ai writing tool", "content creation", "campaign ideas"],
    seoTitle: "ChatGPT for Growth Teams | Alternatives, Use Cases & Workflow Ideas",
    seoDescription: "Review ChatGPT for growth workflows, content drafting, campaign planning, and alternatives for creators, stores, and marketers.",
  },
  {
    id: "tool-semrush",
    slug: "semrush",
    name: "Semrush",
    initials: "SE",
    tagline: "Keyword research and competitor insights",
    description: "Find search opportunities, audit competitors, and prioritize content topics with measurable demand.",
    category: "seo",
    categoryLabel: "SEO & Research",
    bestFor: "SEO teams and founders",
    pricingCue: "Trial available",
    tags: ["SEO", "Research"],
    alternatives: [
      { name: "Ahrefs", cue: "Backlink research" },
      { name: "Ubersuggest", cue: "Starter SEO" },
      { name: "Similarweb", cue: "Market insight" },
    ],
    featured: true,
    verified: true,
    ctaLabel: "View tool",
    searchTerms: ["semrush alternative", "seo tool", "keyword research", "competitor research"],
    seoTitle: "Semrush for Growth Teams | Alternatives, SEO Use Cases & Research Ideas",
    seoDescription: "Explore Semrush for keyword research, competitor analysis, SEO planning, and alternatives for growth teams.",
  },
  {
    id: "tool-zapier-ai",
    slug: "zapier-ai",
    name: "Zapier AI",
    initials: "ZA",
    tagline: "AI automation across app workflows",
    description: "Connect forms, agents, chatbots, tables, and thousands of app integrations for growth operations.",
    category: "automation",
    categoryLabel: "Automation",
    bestFor: "Lean teams and agencies",
    pricingCue: "Free start",
    tags: ["Automation", "Integrations"],
    alternatives: [
      { name: "Make", cue: "Visual automation" },
      { name: "Klaviyo", cue: "Lifecycle flows" },
      { name: "Typeform", cue: "Form routing" },
    ],
    featured: true,
    verified: true,
    ctaLabel: "View tool",
    searchTerms: ["zapier alternative", "ai automation", "workflow automation", "app integrations"],
    seoTitle: "Zapier AI for Growth Workflows | Alternatives & Automation Ideas",
    seoDescription: "Use Zapier AI to connect growth workflows, automate handoffs, and compare alternatives for lean teams.",
  },
  {
    id: "tool-promptmonitor",
    slug: "promptmonitor",
    name: "Promptmonitor",
    initials: "PM",
    tagline: "Track how AI assistants mention your brand",
    description: "Measure brand visibility inside AI answers and monitor whether prospects discover your company through assistants.",
    category: "analytics",
    categoryLabel: "Analytics & Conversion",
    bestFor: "Brands and agencies",
    pricingCue: "Check plan",
    tags: ["AI visibility", "Analytics"],
    alternatives: [
      { name: "Peec AI", cue: "AI search tracking" },
      { name: "Profound", cue: "Answer analytics" },
      { name: "Scrunch AI", cue: "Brand monitoring" },
    ],
    featured: true,
    verified: true,
    ctaLabel: "View tool",
    searchTerms: ["promptmonitor alternative", "ai visibility", "ai search analytics", "brand mentions"],
    seoTitle: "Promptmonitor Alternatives & AI Visibility Tracking Ideas | DeepLinkOS",
    seoDescription: "Compare Promptmonitor use cases and alternatives for tracking brand visibility across AI assistants.",
  },
  {
    id: "tool-canva-magic-studio",
    slug: "canva-magic-studio",
    name: "Canva Magic Studio",
    initials: "CM",
    tagline: "Fast campaign visuals and branded assets",
    description: "Create ads, social posts, presentation visuals, and campaign graphics without slowing down the content calendar.",
    category: "content",
    categoryLabel: "Content & Creative",
    bestFor: "Creators and stores",
    pricingCue: "Free plan",
    tags: ["Design", "Creative"],
    alternatives: [
      { name: "Adobe Express", cue: "Brand templates" },
      { name: "Figma", cue: "Design systems" },
      { name: "Kittl", cue: "Product visuals" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["canva alternative", "ai design tool", "social media graphics", "campaign visuals"],
    seoTitle: "Canva Magic Studio for Growth Content | Alternatives & Creative Use Cases",
    seoDescription: "Explore Canva Magic Studio for campaign visuals, social content, and creative alternatives for growth teams.",
  },
  {
    id: "tool-descript",
    slug: "descript",
    name: "Descript",
    initials: "DE",
    tagline: "Edit videos and podcasts from text",
    description: "Turn interviews, tutorials, and product demos into short clips, transcripts, and repurposed content.",
    category: "content",
    categoryLabel: "Content & Creative",
    bestFor: "Video creators",
    pricingCue: "Free start",
    tags: ["Video", "Podcast"],
    alternatives: [
      { name: "CapCut", cue: "Short videos" },
      { name: "Riverside", cue: "Recording" },
      { name: "OpusClip", cue: "Clip generation" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["descript alternative", "ai video editor", "podcast editing", "repurpose content"],
    seoTitle: "Descript for Content Teams | Alternatives & Video Workflow Ideas",
    seoDescription: "Review Descript for editing videos, podcasts, transcripts, and content repurposing workflows.",
  },
  {
    id: "tool-perplexity",
    slug: "perplexity",
    name: "Perplexity",
    initials: "PX",
    tagline: "Research with cited AI answers",
    description: "Explore markets, customer questions, product angles, and competitor positioning before publishing content.",
    category: "seo",
    categoryLabel: "SEO & Research",
    bestFor: "Researchers and writers",
    pricingCue: "Free start",
    tags: ["Research", "Content"],
    alternatives: [
      { name: "ChatGPT", cue: "Drafting" },
      { name: "Google AI Mode", cue: "Search context" },
      { name: "Claude", cue: "Analysis" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["perplexity alternative", "ai research tool", "market research", "content research"],
    seoTitle: "Perplexity for Growth Research | Alternatives & Use Cases",
    seoDescription: "Use Perplexity for growth research, content planning, customer questions, and AI research alternatives.",
  },
  {
    id: "tool-surfer",
    slug: "surfer",
    name: "Surfer",
    initials: "SU",
    tagline: "SEO content briefs and optimization",
    description: "Build article briefs, compare SERP patterns, and tighten on-page content before publishing.",
    category: "seo",
    categoryLabel: "SEO & Research",
    bestFor: "Content marketers",
    pricingCue: "Paid",
    tags: ["SEO", "Briefs"],
    alternatives: [
      { name: "Clearscope", cue: "Content quality" },
      { name: "Frase", cue: "Briefs" },
      { name: "NeuronWriter", cue: "Optimization" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["surfer seo alternative", "seo content tool", "content brief", "on page seo"],
    seoTitle: "Surfer SEO Alternatives & Content Optimization Workflows | DeepLinkOS",
    seoDescription: "Compare Surfer SEO use cases and alternatives for briefs, on-page optimization, and content growth.",
  },
  {
    id: "tool-opusclip",
    slug: "opusclip",
    name: "OpusClip",
    initials: "OC",
    tagline: "Turn long videos into short clips",
    description: "Repurpose webinars, podcasts, creator videos, and product demos into social-ready clips.",
    category: "social",
    categoryLabel: "Social Growth",
    bestFor: "Short-form creators",
    pricingCue: "Free start",
    tags: ["Shorts", "Repurpose"],
    alternatives: [
      { name: "Captions", cue: "Video edits" },
      { name: "Submagic", cue: "Captions" },
      { name: "Descript", cue: "Full editing" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["opusclip alternative", "short form video", "ai clips", "social growth"],
    seoTitle: "OpusClip Alternatives & Short-Form Growth Workflows | DeepLinkOS",
    seoDescription: "Explore OpusClip and alternatives for turning long-form videos into short social clips.",
  },
  {
    id: "tool-buffer-ai",
    slug: "buffer-ai",
    name: "Buffer AI",
    initials: "BU",
    tagline: "Plan and schedule social content",
    description: "Draft post variations, queue campaigns, and keep creator or brand channels consistent.",
    category: "social",
    categoryLabel: "Social Growth",
    bestFor: "Solo creators and small teams",
    pricingCue: "Free plan",
    tags: ["Scheduling", "Social"],
    alternatives: [
      { name: "Later", cue: "Visual calendar" },
      { name: "Metricool", cue: "Reporting" },
      { name: "Hootsuite", cue: "Team workflows" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["buffer alternative", "social scheduling", "ai social media tool", "content calendar"],
    seoTitle: "Buffer AI Alternatives & Social Scheduling Ideas | DeepLinkOS",
    seoDescription: "Review Buffer AI for social scheduling, post ideation, and alternatives for creators and teams.",
  },
  {
    id: "tool-klaviyo-ai",
    slug: "klaviyo-ai",
    name: "Klaviyo AI",
    initials: "KA",
    tagline: "Lifecycle email and SMS for stores",
    description: "Build smarter flows, segments, product messages, and retention campaigns for ecommerce growth.",
    category: "ecommerce",
    categoryLabel: "Ecommerce",
    bestFor: "Shopify and DTC teams",
    pricingCue: "Free start",
    tags: ["Email", "SMS"],
    alternatives: [
      { name: "Omnisend", cue: "Ecommerce email" },
      { name: "Mailchimp", cue: "Starter email" },
      { name: "Postscript", cue: "SMS" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["klaviyo alternative", "ecommerce email", "sms marketing", "shopify ai"],
    seoTitle: "Klaviyo AI for Ecommerce Growth | Alternatives & Lifecycle Ideas",
    seoDescription: "Explore Klaviyo AI for ecommerce email, SMS, segmentation, and alternatives for stores.",
  },
  {
    id: "tool-shopify-magic",
    slug: "shopify-magic",
    name: "Shopify Magic",
    initials: "SM",
    tagline: "AI help inside ecommerce workflows",
    description: "Draft product descriptions, customer replies, and store content without leaving the Shopify workflow.",
    category: "ecommerce",
    categoryLabel: "Ecommerce",
    bestFor: "Store owners",
    pricingCue: "Included tools",
    tags: ["Shopify", "Store ops"],
    alternatives: [
      { name: "Klaviyo AI", cue: "Lifecycle" },
      { name: "Gorgias", cue: "Support" },
      { name: "Canva", cue: "Creative" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["shopify magic alternative", "shopify ai tools", "product descriptions", "ecommerce ai"],
    seoTitle: "Shopify Magic for Store Growth | Alternatives & Ecommerce AI Ideas",
    seoDescription: "Review Shopify Magic for store content, product descriptions, customer replies, and ecommerce AI alternatives.",
  },
  {
    id: "tool-make",
    slug: "make",
    name: "Make",
    initials: "MK",
    tagline: "Visual automation for growth systems",
    description: "Connect leads, spreadsheets, CRMs, notifications, and campaign operations with visual workflows.",
    category: "automation",
    categoryLabel: "Automation",
    bestFor: "Operators and builders",
    pricingCue: "Free start",
    tags: ["No-code", "Ops"],
    alternatives: [
      { name: "Zapier AI", cue: "App coverage" },
      { name: "n8n", cue: "Self-hosting" },
      { name: "Airtable", cue: "Databases" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["make alternative", "automation builder", "no-code automation", "growth operations"],
    seoTitle: "Make Automation Alternatives & Growth Ops Workflows | DeepLinkOS",
    seoDescription: "Compare Make with automation alternatives for growth operations, lead routing, and campaign workflows.",
  },
  {
    id: "tool-typeform-ai",
    slug: "typeform-ai",
    name: "Typeform AI",
    initials: "TF",
    tagline: "Forms, surveys, and lead capture flows",
    description: "Create smarter intake forms, quizzes, lead magnets, and customer research flows.",
    category: "automation",
    categoryLabel: "Automation",
    bestFor: "Lead capture teams",
    pricingCue: "Free start",
    tags: ["Forms", "Lead capture"],
    alternatives: [
      { name: "Tally", cue: "Simple forms" },
      { name: "Fillout", cue: "Power forms" },
      { name: "Jotform", cue: "Templates" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["typeform alternative", "ai form builder", "lead capture", "survey tool"],
    seoTitle: "Typeform AI Alternatives & Lead Capture Workflows | DeepLinkOS",
    seoDescription: "Explore Typeform AI and alternatives for forms, quizzes, lead capture, and customer research.",
  },
  {
    id: "tool-hotjar-ai",
    slug: "hotjar-ai",
    name: "Hotjar AI",
    initials: "HJ",
    tagline: "Understand visitor behavior faster",
    description: "Review heatmaps, feedback, and session insights to spot where landing pages lose high-intent visitors.",
    category: "analytics",
    categoryLabel: "Analytics & Conversion",
    bestFor: "Conversion teams",
    pricingCue: "Free start",
    tags: ["CRO", "Behavior"],
    alternatives: [
      { name: "Microsoft Clarity", cue: "Free analytics" },
      { name: "PostHog", cue: "Product analytics" },
      { name: "FullStory", cue: "Session replay" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["hotjar alternative", "conversion analytics", "heatmap tool", "session replay"],
    seoTitle: "Hotjar AI Alternatives & Conversion Research Workflows | DeepLinkOS",
    seoDescription: "Compare Hotjar AI and alternatives for heatmaps, session insights, feedback, and conversion research.",
  },
  {
    id: "tool-posthog",
    slug: "posthog",
    name: "PostHog",
    initials: "PH",
    tagline: "Product analytics for conversion teams",
    description: "Track funnels, events, experiments, and user behavior across product and marketing journeys.",
    category: "analytics",
    categoryLabel: "Analytics & Conversion",
    bestFor: "Product-led teams",
    pricingCue: "Free start",
    tags: ["Analytics", "Funnels"],
    alternatives: [
      { name: "Amplitude", cue: "Product analytics" },
      { name: "Mixpanel", cue: "Event tracking" },
      { name: "GA4", cue: "Web analytics" },
    ],
    ctaLabel: "View tool",
    searchTerms: ["posthog alternative", "product analytics", "funnel analytics", "event tracking"],
    seoTitle: "PostHog Alternatives & Product Analytics Workflows | DeepLinkOS",
    seoDescription: "Explore PostHog and alternatives for product analytics, funnels, event tracking, and conversion insights.",
  },
];

export const featuredTools = aiTools.filter((tool) => tool.featured);

export const toolCategoryGroups = toolCategories
  .filter((category): category is { id: Exclude<ToolCategory, "all">; label: string } => category.id !== "all")
  .map((category) => ({
    ...category,
    tools: aiTools.filter((tool) => tool.category === category.id),
  }));

export function findTool(slug: string) {
  return aiTools.find((tool) => tool.slug === slug);
}
